server:
  port: 8877
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'news-query-ms'
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/news-db?serverTimezone=CST'
    type: com.alibaba.druid.pool.DruidDataSource 

pagehelper:
  helper-dialect: mysql
  reasonable: true

 